### ISSUE TITLE
In FireFox the arrow game doesn't work. ALSO CHROME DOES NOT LOAD AT ALL.

### ISSUE THREAD

**Issue by ghost** [olavte/MathWorld#1]

**Comment by olavte** [comment]
NEED A BETTER DESCRIPTION OF YOUR PROBLEM, plz provide pictures

**Comment by ghost** [comment]
it is **# _FUCKED_**

**Comment by ghost** [comment]
![maybe](https://user-images.githubusercontent.com/24579534/37822075-b5a77058-2e85-11e8-8188-1a6d3d14dca2.jpg)
